spring.application.name=tripDiary

#Oracle_DB
spring.datasource.url= jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.username=c##tripdiary
spring.datasource.password=384906
spring.datasource.driver-class-name: oracle.jdbc.OracleDriver
